### ISSUE TITLE
Base URL is not configurable

### ISSUE THREAD

**Issue by pohorely** [dapr/dashboard#128]
## Expected Behavior

I expect that the Dapr dashboard will be accessible after exposing it by the ingress / reverse proxy.

## Actual Behavior

The Dapr dashboard does not work if it is exposed by reverse proxy as a virtual directory. (URLs are not reflecting the virtual directory)

A base URL is not configurable (e.g. by an environment variable of the container)

![image](https://user-images.githubusercontent.com/17186121/106636522-4d2ed200-6582-11eb-8ace-d8269f40d3a6.png)

## Steps to Reproduce the Problem

- Deploy Dapr, Dapr dashboard (v 0.3.0) to a K8s cluster by a Helm release
- Deploy the [NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/) to a K8s cluster
- Create an ingress manifest
- Test the web from PC outside of the cluster

example of the ingress manifest:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: main-ingress
  namespace: dapr-system
spec:
  rules:
    - host: some-domain.local
      http:
        paths:
          - path: /dapr-dashboard/(.*)
            backend:
              serviceName: dapr-dashboard
              servicePort: 8080
  tls:
    - hosts:
        - some-domain.local
      secretName: tls-some-domain

```

## Release Note

RELEASE NOTE: **FIX** Configuration of the base URL
