### ISSUE TITLE
Outdated Zipkin YAML configuration structure

### ISSUE THREAD

**Issue by mmisztal1980** [dapr/dashboard#138]
## Expected Behavior

When inspecting the component's configuration I'd expect to see an up-to-date yaml structure  of that component's config

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
```

## Actual Behavior

When clicking on a dashboard zipkin component an outdated YAML structure is displayed

## Steps to Reproduce the Problem

- Run `dapr dashboard` 
- Open a browser tab and navigate to the dashboard url
- In the left-hand side vertical menu click on the "grid" icon to navigate to `dapr components` page
- click on `zipkin`
- click on the `configuration` tab
An outdated yaml structure of the component is displayed

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
spec:
  type: exporters.zipkin
  metadata:
  - name: enabled
    value: "true"
  - name: exporterAddress
    value: http://localhost:9411/api/v2/spans
```

## Release Note

RELEASE NOTE: **FIX** Fixed incorrectly displayed zipkin component yaml structure in the dashboard
