### ISSUE TITLE
Dashboard running inside Docker-compose

### ISSUE THREAD

**Issue by mexanichp** [dapr/dashboard#172]
Hey,

I'm setting up a local environment with `docker-compose.yaml`  [following this guide](https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/#run-using-docker-compose) and I'm wondering is it possible to include the dashboard in the compose configuration as well? What I've tried so far:
```yaml 
## ... several services with dapr sidecars and custom-network and components volumes

placement:
  image: "daprio/dapr"
  command: ["./placement", "-port", "50006"]
  ports:
    - "50006:50006"
  networks:
    - custom-network

dapr-dashboard:
  image: "daprio/dashboard"
  ports:
    - "8888:8080"
  networks:
    - custom-network

networks:
  custom-network:
```

The configuration itself works fine - I was able to invoke one service from another via dapr service invocation but dashboard doesn't recognize dapr sidecar containers, components:
![image](https://user-images.githubusercontent.com/14793229/134689992-f6fb4564-7f20-483b-a0d3-5817ef7643d9.png)

I'm wondering is there any way to somehow point Dashboard to the app-ids of services or any other way to make it work?

Thanks!
