### ISSUE TITLE
Dashboard: User-configurable Base Href in helm deployment

### ISSUE THREAD

**Issue by lisy09** [dapr/dashboard#178]
## Describe the proposal
As https://github.com/dapr/dashboard/pull/168 provides the method to configurate base href for dapr-dashboard, it is better to make this base href configurable also in helm based deployment.

modify: https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_dashboard/templates/dapr_dashboard_deployment.yaml

from:
```yaml
...

        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
...
```
to:

from:
```yaml
...

        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.env.basehref }}
         - name: SERVER_BASE_HREF
            value: {{ .Values.env.basehref }}
{{- end }}
...
```
