### ISSUE TITLE
Prisma Cloud Scan fails for DAPR dashboard deployment

### ISSUE THREAD

**Issue by mustaFAB53** [dapr/dashboard#278]
## Describe the proposal
Prisma Cloud Scan fails for following parameters for DAPR dashboard deployment

- Mount container's root filesystem as read only
- Do not disable default seccomp profile
- Restrict container from acquiring additional privileges

I am not able to find relevant support to resolve the same in latest dapr dashboard 0.15.0 helm chart

Expect following feature support in the helm chart:
```
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault
```
