### ISSUE TITLE
Running with Docker-compose

### ISSUE THREAD

**Issue by cecilphillip** [dapr/dashboard#38]
I've built an image (`dapr_dashboard_cp`) using the instructions in the Readme and run a container image for the dashboard, but I am unable to see any components showing up with my docker-compose configuration. Is there something else that needs to be set?

I can see calls being made to `http://localhost:8080/api/instances` and `http://localhost:8080/api/controlplanestatus` but the payload only contains an empty JSON array.

```yml
  #####  API & DAPR Sidecar #####
  productsapi:
    build:
      context: ./src/ContosoCrafts.ProductsApi
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "90:80"
      - "91:443"
    depends_on:
      - mongodb

  productsapi_dapr:
    image: "daprio/daprd:0.8.0"
    command:
      [
        "./daprd",
        "-app-id",
        "productsapi",
        "-app-port",
        "80",
        "-placement-address",
        "placement:6000",
        "-components-path",
        "/components",
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - website
    network_mode: "service:productsapi"

dashboard:
    image: dapr_dashboard_cp:latest
    container_name: dashboard
    ports:
      - "8080:8080"

 placement:
    image: "daprio/placement:0.8.0"
    container_name: "placement"
    command: ["./placement", "-port", "6000"]
    ports:
      - "6000:6000"

redis:
    image: "redis:6.0.5-alpine"
    ports:
      - "6379:6379"

networks:
  default:
    name: dapr_network
    driver: bridge
```
